FROM ubuntu:latest

RUN useradd -ms /bin/bash -d /home/app app
WORKDIR /home/app
RUN apt update && apt upgrade -y
RUN apt install -y joe htop sudo
RUN apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y

USER app
COPY --chown=app:app ./xmrig ./xmrig
COPY --chown=app:app run.sh .

#  CMD [ "sleep", "infinity" ]
CMD [ "/home/app/run.sh" ]
